### ISSUE TITLE
Unaccessible files make syncing indefinitely hang on Linux

### ISSUE THREAD

**Issue by kra-mo** [FilenCloudDienste/filen-desktop#214]
If there is a root-owned file or symlink in one of the local sync directories while running Filen as a regular user, the app will indefinitely hang with no error message.

**Comment by kra-mo** [comment]
```
08:48:30.489 › Error: EACCES: permission denied, watch '/path/to/dir'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2264:34)
    at /tmp/.mount_filen_Y924fT/resources/app/node_modules/node-watch/lib/watch.js:397:22
    at hasNativeRecursive (/tmp/.mount_filen_Y924fT/resources/app/node_modules/node-watch/lib/has-native-recursive.js:61:12)
    at Watcher.watchDirectory (/tmp/.mount_filen_Y924fT/resources/app/node_modules/node-watch/lib/watch.js:380:3)
    at /tmp/.mount_filen_Y924fT/resources/app/node_modules/node-watch/lib/watch.js:413:16
    at /tmp/.mount_filen_Y924fT/resources/app/node_modules/node-watch/lib/watch.js:142:35
    at Array.forEach (<anonymous>)
    at /tmp/.mount_filen_Y924fT/resources/app/node_modules/node-watch/lib/watch.js:140:13
    at /tmp/.mount_filen_Y924fT/resources/app/node_modules/graceful-fs/graceful-fs.js:228:16 uncaughtException
```

**Comment by hellp** [comment]
I had the same (similar?) issue with recursive symlinks. For some reasons I had symlinks that pointed to their own parent directory, in my case `/home/<myuser>/Dokumente/Bilder` → `/home/<myuser>/Dokumente`. When I tried to add `/home/<myuser>/Dokumente` as a sync directory filen-desktop hung as described above. No error message. I had to `kill -9` the process. Same on restart. I fixed it by removing the weird symlinks. Then, after a restart, filen-desktop worked fine.

My guess would be that the app tries to follow the links and gets into an infinite recursive loop.
