### ISSUE TITLE
Rclone S3 PutObject - Forbidden: Invalid credentials.

### ISSUE THREAD

**Issue by gdmn** [FilenCloudDienste/filen-desktop#79]
**Describe the bug**
I'm trying to use S3 on filen-desktop. I can list files (`rclone ls filen3:` and `rclone lsd filen3:`), but I cannot copy files to Filen S3 backend.

**To Reproduce**
1. Enable local S3 server
2. Configure rclone (config below)
3. Execute `rclone lsd filen3:` to verify configuration
4. Execute `rclone copy --ignore-times randomfile filen3:filen/tmp/`

**Expected behavior**
`randomfile` should be copied to `/tmp` directory.

**Screenshots**
Actual behavior:

```
2024/11/13 11:54:41 ERROR : randomfile: Failed to copy: operation error S3: PutObject, https response error StatusCode: 403, RequestID: , HostID: , api error Forbidden: Invalid credentials.
2024/11/13 11:54:41 ERROR : Attempt 1/3 failed with 1 errors and: operation error S3: PutObject, https response error StatusCode: 403, RequestID: , HostID: , api error Forbidden: Invalid credentials.
2024/11/13 11:54:42 ERROR : randomfile: Failed to copy: operation error S3: PutObject, https response error StatusCode: 403, RequestID: , HostID: , api error Forbidden: Invalid credentials.
```

**OS (please complete the following information):**
 - OS: Arch Linux
 - Version https://github.com/FilenCloudDienste/filen-desktop/releases/download/v3.0.27/Filen_linux_x86_64.AppImage

**Additional context**

`rclone.conf`:

```
[filen3]
type = s3
provider = Other
endpoint = http://127.0.0.1:1901/
force_path_style = true
no_check_bucket = true
region = filen
access_key_id = admin
secret_access_key = admin
```

exported `s3.log`:

```
{"level":50,"time":1731495156021,"pid":36724,"hostname":"hostname","msg":"[auth] {}"}
{"level":50,"time":1731495156022,"pid":36724,"hostname":"hostname","err":{"type":"Error","message":"Authorization header missing","stack":"Error: Authorization header missing\n    at Auth.getAuthDetails (/tmp/.mount_filen_yhDDkb/resources/app.asar/node_modules/@filen/s3/dist/middlewares/auth.js:46:19)\n    at Auth.handle (/tmp/.mount_filen_yhDDkb/resources/app.asar/node_modules/@filen/s3/dist/middlewares/auth.js:70:38)\n    at Layer.handle [as handle_request] (/tmp/.mount_filen_yhDDkb/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/tmp/.mount_filen_yhDDkb/resources/app.asar/node_modules/express/lib/router/index.js:328:13)\n    at /tmp/.mount_filen_yhDDkb/resources/app.asar/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/tmp/.mount_filen_yhDDkb/resources/app.asar/node_modules/express/lib/router/index.js:346:12)\n    at next (/tmp/.mount_filen_yhDDkb/resources/app.asar/node_modules/express/lib/router/index.js:280:10)\n    at IncomingMessage.<anonymous> (/tmp/.mount_filen_yhDDkb/resources/app.asar/node_modules/@filen/s3/dist/middlewares/body.js:32:9)\n    at IncomingMessage.emit (node:events:519:28)\n    at endReadableNT (node:internal/streams/readable:1696:12)"},"msg":"Authorization header missing"}
{"level":50,"time":1731495156022,"pid":36724,"hostname":"hostname","msg":"{}"}
{"level":50,"time":1731495156022,"pid":36724,"hostname":"hostname","err":{"type":"Error","message":"Authorization header missing","stack":"Error: Authorization header missing\n    at Auth.getAuthDetails (/tmp/.mount_filen_yhDDkb/resources/app.asar/node_modules/@filen/s3/dist/middlewares/auth.js:46:19)\n    at Auth.handle (/tmp/.mount_filen_yhDDkb/resources/app.asar/node_modules/@filen/s3/dist/middlewares/auth.js:70:38)\n    at Layer.handle [as handle_request] (/tmp/.mount_filen_yhDDkb/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/tmp/.mount_filen_yhDDkb/resources/app.asar/node_modules/express/lib/router/index.js:328:13)\n    at /tmp/.mount_filen_yhDDkb/resources/app.asar/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/tmp/.mount_filen_yhDDkb/resources/app.asar/node_modules/express/lib/router/index.js:346:12)\n    at next (/tmp/.mount_filen_yhDDkb/resources/app.asar/node_modules/express/lib/router/index.js:280:10)\n    at IncomingMessage.<anonymous> (/tmp/.mount_filen_yhDDkb/resources/app.asar/node_modules/@filen/s3/dist/middlewares/body.js:32:9)\n    at IncomingMessage.emit (node:events:519:28)\n    at endReadableNT (node:internal/streams/readable:1696:12)"},"msg":"Authorization header missing"}
```

**Comment by Dwynr** [comment]
Thanks for reporting.

Fixed via: https://github.com/FilenCloudDienste/filen-s3/commit/3f9c7df315f94a195ab275d3c39e925ca3fab49e
